import bg from './image/bgPics.jpg'
import bg2 from './image/bgpics.jpg'

export const shopData = [
    {
        id: 1,
        image: bg,
        hoverImage: bg2,
        name: 'IB FOOTBALL JERSEY',
        price: 200.00,
        descriptionHead: 'NEW ARRIVAL',
        description: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        materialHead: 'COMPOSITION',
        material: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        care: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.'

    },
    {
        id: 2,
        image: bg,
        hoverImage: bg2,
        name: 'IB STREET TEE',
        price: 300.00,
        descriptionHead: 'NEW ARRIVAL',
        description: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        materialHead: 'COMPOSITION',
        material: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        care: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.'
    },
    {
        id: 3,
        image: bg,
        hoverImage: bg2,
        name: 'IB BRANDED SHORT',
        price: 250.00,
        descriptionHead: 'NEW ARRIVAL',
        description: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        materialHead: 'COMPOSITION',
        material: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        care: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.'
    },
    {
        id: 4,
        image: bg,
        hoverImage: bg2,
        name: 'IB STREET PANT',
        price: 460.00,
        descriptionHead: 'NEW ARRIVAL',
        description: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        materialHead: 'COMPOSITION',
        material: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        care: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.'
    },
    {
        id: 5,
        image: bg,
        hoverImage: bg2,
        name: 'IB GIRL GOWN',
        price: 255.00,
        descriptionHead: 'NEW ARRIVAL',
        description: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        materialHead: 'COMPOSITION',
        material: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        care: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.'
    },
    {
        id: 6,
        image: bg,
        hoverImage: bg2,
        name: 'IB FOOTBALL JERSEY',
        price: 200.00,
        descriptionHead: 'NEW ARRIVAL',
        description: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        materialHead: 'COMPOSITION',
        material: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        care: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.'

    },
    {
        id: 7,
        image: bg,
        hoverImage: bg2,
        name: 'IB FOOTBALL JERSEY',
        price: 200.00,
        descriptionHead: 'NEW ARRIVAL',
        description: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        materialHead: 'COMPOSITION',
        material: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        care: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.'

    },
    {
        id: 8,
        image: bg,
        hoverImage: bg2,
        name: 'IB FOOTBALL JERSEY',
        price: 200.00,
        descriptionHead: 'NEW ARRIVAL',
        description: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        materialHead: 'COMPOSITION',
        material: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        care: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.'

    },
    {
        id: 9,
        image: bg,
        hoverImage: bg2,
        name: 'IB FOOTBALL JERSEY',
        price: 200.00,
        descriptionHead: 'NEW ARRIVAL',
        description: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        materialHead: 'COMPOSITION',
        material: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        care: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.'

    },
    {
        id: 10,
        image: bg,
        hoverImage: bg2,
        name: 'IB FOOTBALL JERSEY',
        price: 200.00,
        descriptionHead: 'NEW ARRIVAL',
        description: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        materialHead: 'COMPOSITION',
        material: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        care: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.'

    },
    {
        id: 11,
        image: bg,
        hoverImage: bg2,
        name: 'IB FOOTBALL JERSEY',
        price: 200.00,
        descriptionHead: 'NEW ARRIVAL',
        description: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        materialHead: 'COMPOSITION',
        material: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        care: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.'

    },
    {
        id: 12,
        image: bg,
        hoverImage: bg2,
        name: 'IB FOOTBALL JERSEY',
        price: 200.00,
        descriptionHead: 'NEW ARRIVAL',
        description: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        materialHead: 'COMPOSITION',
        material: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        care: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.'

    },

    {
        id: 13,
        image: bg,
        hoverImage: bg2,
        name: 'IB FOOTBALL JERSEY',
        price: 200.00,
        descriptionHead: 'NEW ARRIVAL',
        description: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        materialHead: 'COMPOSITION',
        material: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        care: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.'

    },
    {
        id: 14,
        image: bg,
        hoverImage: bg2,
        name: 'IB FOOTBALL JERSEY',
        price: 200.00,
        descriptionHead: 'NEW ARRIVAL',
        description: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        materialHead: 'COMPOSITION',
        material: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        care: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.'

    },
    {
        id: 15,
        image: bg,
        hoverImage: bg2,
        name: 'IB FOOTBALL JERSEY',
        price: 200.00,
        descriptionHead: 'NEW ARRIVAL',
        description: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        materialHead: 'COMPOSITION',
        material: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.',
        care: 'SHIRT IN HOVEN FABRIC WITH AN EASY-IRN FINISH. TURN-DOWN COLLAR, A CLASSIC FRONYT AND A YOKE AT THE BACK. LONG SLEEVES WITH ADJUSTABLE BUTTONING AT THE CUFFS AND A SLEEV PLACKET WITH A LINK BUTTON. GENTLY ROUNDED HEM. SLIM FIT THAT HUGS THE CONTOURS OF YOUR BODY, CREATING A FITTED SILHOUETTE.'

    },
    
]